[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-20_x", "python3", "sqlite"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.12.3 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter appliance-buddy-api run build"
]

[start]
cmd = "pnpm --filter appliance-buddy-api run start"

[healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3